replicaCount: 1
image:
  repository: ghcr.io/uvarc/omegasync
  pullPolicy: Always
  tag: prod-1.0.12
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi
nodeSelector: {}
tolerations: []
affinity: {}
