apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "omegasync.fullname" . }}-submit-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: ghcr.io/uvarc/uvarc-unified-service-base:develop
            imagePullPolicy: Always
            command: ["/bin/bash", "/opt/local/non_root_user/uvarc_unified_service/bin/pull-newkey.sh"]
            volumeMounts:
            - name: ssh-key-volume
              mountPath: "/etc/ssh-key"
            env:
            - name: REMOTE_SCRIPT
              value: "/standard/CHRL-Space/omegasync/yamls/codes"
            - name: USERID
              value: "ns6pf"
            resources:
              limits:   
                cpu: "0.5"
                memory: 512Mi
              requests: 
                cpu: "0.5"
                memory: 512Mi
          volumes:
          - name: ssh-key-volume
            secret:
              secretName: ns6pf-ssh-key
              defaultMode: 256
          restartPolicy: OnFailure
      ttlSecondsAfterFinished: 86400
