apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "omegasync.fullname" . }}-submit-cronjob
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/bash
                - -c
                - /srv/shiny-server/yaml_files/codes/submit.sh
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: yaml-files
                  mountPath: /srv/shiny-server/yaml_files
          volumes:
            - name: yaml-files
              persistentVolumeClaim:
                claimName: omegasync-cephfs-pvc
          restartPolicy: OnFailure