---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    #    nginx.org/websocket-services: "{{ include "omegasync.fullname" . }}"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    nginx.org/proxy-connect-timeout: "600s"
    nginx.org/proxy-read-timeout: "600s"
    nginx.org/proxy-send-timeout: "600s"
  name: {{ include "omegasync.fullname" . }}
spec:
  rules:
    - host: {{ include "omegasync.fullname" . }}.pods.uvarc.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "omegasync.fullname" . }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ include "omegasync.fullname" . }}.pods.uvarc.io
      secretName: {{ include "omegasync.fullname" . }}-nginx-tls-ingress-secret