apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "omegasync.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-rbd-sc
  selector:
    matchLabels:
      app: "omegasync"