---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "omegasync.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: omegasync-cephfs-pv
  storageClassName: csi-cephfs-sc
  selector:
    matchLabels:
      app: "omegasync"