replicaCount: 1

image:
  repository: ghcr.io/uvarc/omegasync
  pullPolicy: Always
  tag: 1.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

resources:
   limits:
     cpu: 32
     memory: 64Gi
   requests:
     cpu: 32
     memory: 64Gi

nodeSelector: {}

tolerations: []

affinity: {}
