name: Docker Build CI

on:
  push:
    tags: ['*.*']

jobs:
  build-for-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variables
        run: |
          echo "BUILD_PROJ=omegasync" >> $GITHUB_ENV

#      - name: Extract branch name
#        run: |
#          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
#          echo "Building release version $BRANCH_NAME"
#          echo "BUILD_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
#        id: extract_branch

      - name: Get Tag Version
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo "IMAGE_TAG: ${IMAGE_TAG}"
          yq eval ".image.tag = \"${IMAGE_TAG}\"" -i kubernetes/values.yaml
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: docker-${{ github.sha }}
          restore-keys: |
            docker-

      - name: Build and push
#        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:latest
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ env.IMAGE_TAG }}
#            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ github.ref_name }}

#      - name: Build and push (Other Branches)
#        if: github.ref != 'refs/heads/main'
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ./docker/Dockerfile
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: |
#            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ github.ref_name }}

      - name: Push Version to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci] Bump Version - ${{ env.IMAGE_TAG }}"
          branch: main
          file_pattern: 'kubernetes/values.yaml'
          commit_user_name: GitHub Actions Bot
          commit_user_email: github@virginia.edu
          commit_author: GitHub Actions <github@virginia.edu>
          skip_fetch: true
